/* Generated By:JJTree&JavaCC: Do not edit this line. eg1Constants.java */
package modelCheckCTL.util;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface eg1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NOT = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int THEN = 8;
  /** RegularExpression Id. */
  int ALL = 9;
  /** RegularExpression Id. */
  int EXISTS = 10;
  /** RegularExpression Id. */
  int FUTURE = 11;
  /** RegularExpression Id. */
  int GLOBALY = 12;
  /** RegularExpression Id. */
  int NEXT = 13;
  /** RegularExpression Id. */
  int UNTIL = 14;
  /** RegularExpression Id. */
  int ATOM = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"->\"",
    "\"A\"",
    "\"E\"",
    "\"F\"",
    "\"G\"",
    "\"X\"",
    "\"U\"",
    "<ATOM>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
  };

}
