/* Generated By:JavaCC: Do not edit this line. eg1TreeConstants.java Version 5.0 */
package modelCheckCTL.util;

public interface eg1TreeConstants
{
  public int JJTFORMULA = 0;
  public int JJTVOID = 1;
  public int JJTEXPR = 2;
  public int JJTCONNECTIVE = 3;
  public int JJTATOM = 4;


  public String[] jjtNodeName = {
    "Formula",
    "void",
    "Expr",
    "Connective",
    "Atom",
  };
}
/* JavaCC - OriginalChecksum=23850595f98be71780994d5093590e51 (do not edit this line) */
